### ISSUE TITLE
[SUGGESTION] Ability to change where lovebrew looks for files, and builds files

### ISSUE THREAD

**Issue by ajusa** [TurtleP/lovebrew#1]
Ideally, all of these would be configurable through the toml file rather than the command line.
**Game Source Directory**
Some way to change where lovebrew looks for the game source. For example, someone could have `lovebrew.toml` in a parent directory, and then have their source lua files inside of `src`. 

**Game Build Directory**
Ability to set where the built files go, relative to the lovebrew.toml file

**Binary LovePotion Files**
Changing where these files are located would be very nice. For example, if a build script fetches a specific version from Github when it is ran, it would be a bit cumbersome to move it to `.lovepotion` and set up the environment variables each time. Instead, have a config variable that is relative to the toml file.

**Changing where the icons are**
Setting the icons filepath for 3ds and switch, again relative to the toml file.

**Comment by TurtleP** [comment]
The only thing that is unnecessary is the binary check. This was actually dealt with! I made it so it would check `~/.lovepotion` for the files. However, if you mean something like multi-version usage where you can set a different name, like `thisbuildhasmorelogging.elf` or `thisisasecretdevbuild.elf`, that makes a lot more sense.

I also thought about adding a 'sync with GitHub' option so that it would fetch the latest elf files, but I'm not sure about doing that if we're doing multi-version management.

**Comment by ajusa** [comment]
Multi-version usage isn't part of my use case. I want to have it check a different filepath (again, relative to the toml) when looking for the bin files. 
My project structure has a `bin` folder that I was going to put the lovepotion binaries in, rather than downloading them to the home directory. So I want lovebrew to look inside of the `bin` folder instead.
This also might make it more cross platform - not sure how Windows handles a home directory. It is possible to get all the devkitpro things to run on windows using a docker file too.

**Comment by ajusa** [comment]
```
├── build/
├── ftp.in
├── icons/
├── lovebrew.toml
├── README.md
├── spec/
├── src/
└── bin/
```
Example directory structure I am trying to get lovebrew to work with. LovePotion binaries in bin, lua source files in src, the icons in icons, and I want the build files to be output in build. In this case, build and bin are inside of a `.gitignore`, so I won't be pushing lovepotion binaries to git.

**Comment by ajusa** [comment]
The build directory output doesn't seem to work quite yet, it just popped the nro in my cwd.

**Comment by TurtleP** [comment]
The nro (and 3dsx) will always be output to the root directory where the config file is. I can change this, if necessary.
