### ISSUE TITLE
Error on switch build, "failed to open input nacp!"

### ISSUE THREAD

**Issue by EggoTheSquirrel** [TurtleP/lovebrew#11]
I am trying to make a simple test game and lovebrew build fails to open the input nacp and cannot open the game.love file.

I ran lovebrew init and edited the config file thus:
-targets only switch
-clean = true
-moved icon path into dependencies subfolder
-changed name, description, author, and version
I have the switch.elf and switch.elf.nacp in the AppData/Roaming/.lovebrew
I made a simple LOVE program that would draw a few rectangles

I expected the program to compile my code into a .nro file.

![image](https://user-images.githubusercontent.com/33180708/127785643-7a290652-f82f-4ccd-ac80-9f0a463b5b45.png)

OS is Windows 10

Lovebrew version 0.4.0

**Comment by TurtleP** [comment]
This should be resolved in 0.5.0, sorry for the late reply. Should be released soon.

**Comment by EggoTheSquirrel** [comment]
Thanks for fixing it! Works great now.
