### ISSUE TITLE
Problem: Cannot run in devkitpro docker image

### ISSUE THREAD

**Issue by fontire** [TurtleP/lovebrew#12]
I tried downloading the Linux binary to run the devkitpro docker container. I get this error:

```
./lovebrew: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./lovebrew)
```

I also get that error running on my regular system.

**Comment by TurtleP** [comment]
This was something I ran into as well, I think it has to do with the nim version being used to compile it, which was development. 0.5.0 uses the latest stable version now, so I *think* it shouldn't be an issue any longer.

**Comment by fontire** [comment]
Thank you. I'll have a look.

Have you tried the Docker container? It would be great to have this easy to deploy inside that. I would like to get the "hello world" example working.

**Comment by fontire** [comment]
Trying 0.5.0 I get
```
./lovebrew: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./lovebrew)
./lovebrew: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./lovebrew)
```

**Comment by TurtleP** [comment]
Alright. I'll ask the nim Discord about this. I'm not sure why this is still an issue. I'd expect it to be statically compiled so that this doesn't happen, honestly.

**Comment by fontire** [comment]
I would expect it to be, too. By the way, I was able to build `lovebrew` by changing the requirement to 1.4.8 :P Not sure if that would cause any issues.

However, I'm still not clear on how to set things up and get the `hello world` example running.

**Comment by TurtleP** [comment]
I've updated [the Wiki section](https://lovebrew.org/#/packaging?id=l%c3%96vebrew-application) to reflect this a bit better, hope it helps. There's also comments in the TOML file that clarify what each item does. If there's anything specific, please let me know and I will gladly help. 

As for the nim version, I think my desktop may have compiled on development and not 1.4.8, but I will double check. I'm running Ubuntu 21.04 on WSL2 there.

I'll see if the nim Discord can help me out (didn't get around to it yesterday woops)

**Comment by TurtleP** [comment]
I double checked, I am running nim 1.4.8, so that shouldn't be the issue. Checking to see what I can do about this GLIBC error you've been getting.

**Comment by TurtleP** [comment]
Alright, turns out that, of course, I had to manually add the static linking flag. I tested it on Ubuntu 18.04 (via repl.it) and it runs. Hopefully it works for you now. I'll add a detailed tutorial for 'Hello World' using LÖVEBrew on the Wiki as well.

Let me know if 0.5.1 fixes your issue, and if so, feel free to close this.

**Comment by fontire** [comment]
Thank you! The new version works.

My next question is why do I need `3dsxtool` to build for Switch? I set the build target for only Switch.

But that is another topic. Should I open a new issue for getting the build working?

**Comment by TurtleP** [comment]
That is odd.. I thought I made it so that it *shouldn't* be checking for that on Switch builds. Sure, open an issue as it'll help me keep track of that.

**Comment by fontire** [comment]
Will do. I also got a "hello world" to build and run! Huzzah :)

Thanks!
