### ISSUE TITLE
[Bug]: 3dsxtool required for Switch

### ISSUE THREAD

**Issue by fontire** [TurtleP/lovebrew#15]
### Software Version

0.5.1 (Latest)

### What Happened?

When trying to build for Switch, lovebrew requires `3dsxtool`.

This happens even when the configuration file only has Switch as a target.

### What was Expected?

`3dsxtool` should not be needed for Switch builds.

### Operating System

Linux

### Operating System Version

Debian

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Fixed in 0.5.3, sorry for the oversight.

**Comment by fontire** [comment]
Thank you!
