### ISSUE TITLE
[Bug]: Build hello world example success, but can not get it to work on switch.

### ISSUE THREAD

**Issue by iamcco** [TurtleP/lovebrew#22]
### Software Version

0.5.5 (Latest)

### What Happened?

App can not work on switch.

### What was Expected?

App should work on switch.

### Operating System

macOS

### Operating System Version

MacOS 11.6

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by iamcco** [comment]
[01667377874_01004b10157f2000.log](https://github.com/lovebrew/lovebrew/files/9920285/01667377874_01004b10157f2000.log)

log in the crash report directory

**Comment by TurtleP** [comment]
This isn't for LÖVE Potion bugs, this is for LÖVEBrew. Please open your issue on the correct repository.

**Comment by iamcco** [comment]
Sorry for that, I thought it was bug of lovebrew.
