### ISSUE TITLE
[Bug]: LÖVEBrew 0.7.0 does not launch on Windows 10

### ISSUE THREAD

**Issue by portalsam1** [TurtleP/lovebrew#27]
### Software Version

0.5.3 (Latest)

### What Happened?

The software version field of this form lists 0.5.3 as the latest version so apologies if this isn't the right place.

I've downloaded LÖVEBrew 0.7.0 and placed it into %appdata%/lovebrew/, and added it to my PATH variable as instructed.

Launching lovebrew.exe produces: "could not load: (libcrypto-1_1-x64|libeay64).dll"
I have openSSL installed through DevKitPro MSYS2 and a standalone Windows version, and have tried finding the dlls it is asking for and putting them in the same directory as the executable which produces even more missing dll issues.

![image](https://github.com/lovebrew/lovebrew/assets/41414314/c2182fd5-0e01-4e8d-b538-a591a362fc53)

### What was Expected?

lovebrew.exe should run with the instructions provided on the GitHub readme.md

### Operating System

Windows

### Operating System Version

Windows 10 Home 22H2 19045.2965

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Weird.. it does work on Windows 11 for me. I'll check in with the nim community and see what's up. I do compile it with SSL.

**Comment by TurtleP** [comment]
Fixed it. New release based on #28
