### ISSUE TITLE
Error building 3dsx files

### ISSUE THREAD

**Issue by Bazket571** [TurtleP/lovebrew#3]
When I try to build my game, this show up

`F:\Programming\Love Framework\lovebrew-master>lovebrew -v`

`[2020-06-14 18:58:47] / ERROR / Invalid config key 'artifacts'. Expected one of: author, description, name, targets, version, zip_artifacts`

`[2020-06-14 18:58:47] / CRITICAL / Failed to build for Nintendo 3DS ('bool' object is not callable)`

**Comment by TurtleP** [comment]
Try using 0.2.0, it has a few upgrades and fixes. Let me know how it goes.

**Comment by TurtleP** [comment]
Discussed in the discord server, seems to be resolved.
