### ISSUE TITLE
Lovebrew creates .3dsx file, but asks for a `game` directory

### ISSUE THREAD

**Issue by kiiwiiwastaken** [TurtleP/lovebrew#5]
I have made a basic LovePotion file with a .ogg file and it compiles successfully, but when I try to run the .3dsx file in the homebrew launcher I get this output:

```
Error

boot.lua:702: No code to run. Your game might be packaged incorrectly. Make sure main.lua is at the top level of the zip file.

Traceback
    [C]: in function 'error'
    [C]: in function 'xpcall'
    [C]: in function 'xpcall'
```

Here is the directory structure:
```
mua/
├── game
│   ├── main.lua
│   └── song.ogg
└── lovebrew.toml
```
Here's a link to the `lovebrew.toml` file since github doesn't support uploading .toml files :( https://0bin.net/paste/UEbIHRlv#eI9XF-+NXKy6NPHEQEKi3hjv+5rKqUGxCqU62/H+Y0k

**Comment by TurtleP** [comment]
I think you accidentally tried to run it with LÖVE. This error isn’t relevant for LÖVE Potion.
